### ISSUE TITLE
Markdown

### ISSUE THREAD

**Issue by idris-maps** [Stephane-panda/datavis#3]
Fais attention à ton markdown:

* pour les titres, n'utilise pas `# h3 Mon titre` mais `###`
* si tu ne reviens qu'une fois à la ligne, il n'a pas de nouveau paragraphe. Si ton intention est un nouveau paragraphe, appuie sur `enter` deux fois

**Comment by idris-maps** [comment]
# marché du travail des ingénieurs médias

## pitch
je vais réaliser un bubble charte qui donne en r le nombre de place de travail pour ce metier en suisse*
regrouper selon 3 grandes industrie

- informatique 
- marketing/communication 
- graphique

ps. un choix d'abstraction arbitraire sera fait principalement sur les metiers de l'informatique hardware

### option 

si j'ai le temps, lorsque l'on clique sur un industrie cela zoom dedans affichant les bulles trop petites pour être significativement visible. Niveau de precision dependra des données 

un deuxieme vue permetra egalement de changer la couleur des bulle en fonction des famille des métier en question

si vraiment je m'ennuie un variation au cours du temps sera disponible. 
ou un story telling 

Si vraiment vraiment je sais plus quoi faire, je ferais un questionnaire qui resultera un serie de tag. chaque metier se verra attribuer un ou plusieurs tag. plus il y aura de match entre les tag des métier et ceux du profile plus on fera monter une variable temperature dans les metiers, on se retrouve avec un carte d'intéret du marché du travail pour un profile donnée

## data 

```
[]
```


#### reflection préalable

mes donnnées serons stocké dans des objet json 
informatique, marketing , graphique 
qui possedera en lui les différent metier qui le compose (ça aidera pour les zoom)
definir la taille, foreach recursif 
visibilité filter >= 
penser au couleur par famille 
variable temperature pour chaque metier 
penser à des tags 


difficultés estimées les données vont fortement impacter les possibilités de ce projets

**Comment by idris-maps** [comment]
Au dessus, c'est la version corrigée. Le tiens ressemble à ça: https://github.com/Stephane-panda/datavis/tree/master/projet

**Comment by Stephane-panda** [comment]
okey
